theme: jekyll-theme-cayman
lsi: false
safe: true
source: /docs
incremental: false
highlighter: rouge
plugins:
  - jekyll-seo-tag
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
google_analytics: UA-164593760-1
